Added opentelemetry-collector rock and tests
canonical/opentelemetry-collector-rock pull request #1
Opened 2024-12-23 16:56 UTC by BON4

### Description
---
* Add rockcraft.yaml
* Add tests
* Add tox.ini

Logs from tests `/charms/knative-operator`
---
`juju status` after all tests are passed:
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.4.6    unsupported  18:30:12+02:00

App                Version  Status   Scale  Charm              Channel        Rev  Address         Exposed  Message
grafana-agent-k8s  0.40.4   waiting      1  grafana-agent-k8s  latest/stable   80  10.152.183.151  no       installing agent
knative-operator            active       1  knative-operator                    0  10.152.183.204  no       

Unit                  Workload  Agent  Address      Ports  Message
grafana-agent-k8s/0*  blocked   idle   10.1.34.181         Missing ['grafana-cloud-config']|['logging-consumer'] for logging-provider; ['grafana-cloud-config']|['send-remote-wr...
knative-operator/0*   active    idle   10.1.34.129         
```

Logs of passed integration tests `tox -vve integration -- --model kubeflow --keep-models`:
```
============================================================================================= test session starts ==============================================================================================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0 -- /home/bon/repos/knative-operators/charms/knative-operator/.tox/integration/bin/python
cachedir: .tox/integration/.pytest_cache
rootdir: /home/bon/repos/knative-operators/charms/knative-operator
configfile: pyproject.toml
plugins: operator-0.35.0, anyio-4.4.0, asyncio-0.21.2
asyncio: mode=auto
collected 4 items                                                                                                                                                                                              

tests/integration/test_charm.py::test_build_and_deploy_with_relations 
------------------------------------------------------------------------------------------------ live log setup ------------------------------------------------------------------------------------------------
INFO     pytest_operator.plugin:plugin.py:734 Connecting to existing model microk8s-localhost:kubeflow on unspecified cloud
------------------------------------------------------------------------------------------------ live log call -------------------------------------------------------------------------------------------------
INFO     pytest_operator.plugin:plugin.py:575 Using tmp_path: /home/bon/repos/knative-operators/charms/knative-operator/.tox/integration/tmp/pytest/kubeflow0
INFO     pytest_operator.plugin:plugin.py:1083 Building charm knative-operator
INFO     pytest_operator.plugin:plugin.py:1088 Built charm knative-operator in 30.74s
INFO     test_charm:test_charm.py:29 Built charm /home/bon/repos/knative-operators/charms/knative-operator/.tox/integration/tmp/pytest/kubeflow0/charms/knative-operator_ubuntu-20.04-amd64.charm
INFO     juju.model:model.py:2098 Deploying local:knative-operator-0
INFO     juju.model:model.py:2972 Waiting for model:
  knative-operator/0 [allocating] waiting: installing agent
INFO     juju.model:model.py:2972 Waiting for model:
  knative-operator/0 [allocating] waiting: agent initialising
INFO     juju.model:model.py:2972 Waiting for model:
  knative-operator/0 [idle] active: 
INFO     charmed_kubeflow_chisme.testing.cos_integration:cos_integration.py:78 deploying grafana-agent-k8s from latest/stable channel
INFO     juju.model:model.py:2098 Deploying ch:amd64/jammy/grafana-agent-k8s-80
INFO     charmed_kubeflow_chisme.testing.cos_integration:cos_integration.py:95 Adding relation: knative-operator:metrics-endpoint and grafana-agent-k8s:metrics-endpoint
INFO     charmed_kubeflow_chisme.testing.cos_integration:cos_integration.py:108 Adding relation: knative-operator:logging and grafana-agent-k8s:logging-provider
INFO     juju.model:model.py:2972 Waiting for model:
  grafana-agent-k8s/0 [allocating] waiting: installing agent
INFO     juju.model:model.py:2972 Waiting for model:
  grafana-agent-k8s/0 [allocating] waiting: agent initialising
INFO     juju.model:model.py:2972 Waiting for model:
  grafana-agent-k8s/0 [executing] blocked: Missing ['grafana-cloud-config']|['logging-consumer'] for logging-provider; ['grafana-cloud-config']|['send-remote-write'] for metrics-endpoint
INFO     juju.model:model.py:2972 Waiting for model:
  grafana-agent-k8s/0 [idle] blocked: Missing ['grafana-cloud-config']|['logging-consumer'] for logging-provider; ['grafana-cloud-config']|['send-remote-write'] for metrics-endpoint
INFO     juju.model:model.py:2972 Waiting for model:
  grafana-agent-k8s/0 [idle] blocked: Missing ['grafana-cloud-config']|['logging-consumer'] for logging-provider; ['grafana-cloud-config']|['send-remote-write'] for metrics-endpoint
PASSED
tests/integration/test_charm.py::test_logging 
------------------------------------------------------------------------------------------------ live log call -------------------------------------------------------------------------------------------------
INFO     charmed_kubeflow_chisme.testing.cos_integration:cos_integration.py:225 found relations [<Relation id=2 knative-operator:logging grafana-agent-k8s:logging-provider>] for knative-operator:logging
INFO     charmed_kubeflow_chisme.testing.cos_integration:cos_integration.py:371 running cmd `relation-get --format=yaml -r 2 - grafana-agent-k8s/0` on unit grafana-agent-k8s/0
PASSED
tests/integration/test_charm.py::test_metrics_enpoint 
------------------------------------------------------------------------------------------------ live log call -------------------------------------------------------------------------------------------------
INFO     charmed_kubeflow_chisme.testing.cos_integration:cos_integration.py:225 found relations [<Relation id=1 grafana-agent-k8s:metrics-endpoint knative-operator:metrics-endpoint>] for knative-operator:metrics-endpoint
INFO     charmed_kubeflow_chisme.testing.cos_integration:cos_integration.py:371 running cmd `relation-get --format=yaml -r 1 --app - knative-operator` on unit knative-operator/0
INFO     charmed_kubeflow_chisme.testing.cos_integration:cos_integration.py:371 running cmd `curl -m 5 -sS localhost:12345/agent/api/v1/metrics/targets` on unit grafana-agent-k8s/0
PASSED
tests/integration/test_charm.py::test_alert_rules 
------------------------------------------------------------------------------------------------ live log call -------------------------------------------------------------------------------------------------
INFO     test_charm:test_charm.py:76 found alert_rules: {'KubeflowServiceIsNotStable', 'KubeflowServiceDown'}
INFO     charmed_kubeflow_chisme.testing.cos_integration:cos_integration.py:225 found relations [<Relation id=1 grafana-agent-k8s:metrics-endpoint knative-operator:metrics-endpoint>] for knative-operator:metrics-endpoint
INFO     charmed_kubeflow_chisme.testing.cos_integration:cos_integration.py:371 running cmd `relation-get --format=yaml -r 1 --app - knative-operator` on unit knative-operator/0
PASSED
---------------------------------------------------------------------------------------------- live log teardown -----------------------------------------------------------------------------------------------
INFO     pytest_operator.plugin:plugin.py:862 Model status:

Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.4.6    unsupported  18:29:59+02:00

App                Version  Status   Scale  Charm              Channel        Rev  Address         Exposed  Message
grafana-agent-k8s  0.40.4   waiting      1  grafana-agent-k8s  latest/stable   80  10.152.183.151  no       installing agent
knative-operator            active       1  knative-operator                    0  10.152.183.204  no       

Unit                  Workload  Agent  Address      Ports  Message
 [...]

2025-01-06 19:11 UTC, sed-i commented on opentelemetry-collector/rockcraft.yaml
> +      cp $CRAFT_PART_BUILD/distributions/otelcol/_build/otelcol $CRAFT_PART_INSTALL
- Should we use `install -D -m755` instead of cp?
- Should we add an `organize` directive to place the binary under `/usr/bin`?

2025-01-06 19:11 UTC, sed-i commented on opentelemetry-collector/rockcraft.yaml
> +  non-root-user:
Let's confirm if `run-user` obviates the non-root-user part.
https://github.com/canonical/rockcraft/pull/233#issuecomment-2573688338

2025-01-06 19:11 UTC, sed-i commented on opentelemetry-collector/tox.ini
tox is ideal for python projects.
Here, let's use just+goss. [Example](https://github.com/canonical/mimir-rock/pull/51).

2025-01-06 19:11 UTC, sed-i commented on opentelemetry-collector/tests/test_rock.py
There isn't a particular need to have a rock test written in python.
Also, existence of files can be asserted with goss.

2025-01-06 23:15 UTC, Abuelodelanada commented on opentelemetry-collector/rockcraft.yaml
> +      cp -r $CRAFT_PART_BUILD/distributions/otelcol/config.yaml $CRAFT_PART_INSTALL
Since otelcol provides a dummy config file in its repo that we use it to build the image. 

Why we should manually duplicate it here?

If upstream modify the config file, manual work should be done in order to keep it in sync.

2025-01-07 02:04 UTC, sed-i commented on opentelemetry-collector/rockcraft.yaml
> +      cp -r $CRAFT_PART_BUILD/distributions/otelcol/config.yaml $CRAFT_PART_INSTALL
Unless we want to keep the same behavior unchanged across rock builds.
For now we can keep using the dummy file from upstream. We can always change that later :)

2025-01-08 03:55 UTC, sed-i commented on .github/.jira_sync_config.yaml
> +    - opentelemetry-collector-rock
In mimir-rock we [omit](https://github.com/canonical/mimir-rock/blob/1abdc8bcd1f955c5543f0248cab9cca89191a876/.github/.jira_sync_config.yaml#L9) the `-rock` suffix.
```suggestion
    - opentelemetry-collector
```

2025-01-08 03:55 UTC, sed-i commented on .github/ISSUE_TEMPLATE/bug_report.yml
Should we remove mentions of juju, charms here?

2025-01-08 03:55 UTC, sed-i commented on .github/pull_request_template.md
> +<!-- To upgrade from an older revision of charmed prometheus, ... -->
```suggestion
<!-- To upgrade from an older revision of otelcol rock, ... -->
```

2025-01-08 03:55 UTC, sed-i commented on README.md
> +* releasing to GHCR at [ghcr.io/canonical/otelcol:dev](https://ghcr.io/canonical/otelcol:dev), when merging to main, for development purposes.
When do we use `opentelemetry-collector` vs `otelcol`?

2025-01-08 03:55 UTC, sed-i commented on 0.110.0/rockcraft.yaml
> +  amd64:
Upstream [cross-compiles](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/f58f0d245a7164cbcaa74448f773a8e3c958a150/.github/workflows/base-release.yaml#L25) to arm64 on amd64. Not sure where rockcraft, oci-factory etc. currently stand with multiarch images, but at some point we'd need an arm64 image.
We can tackle this in a separate issue.

2025-01-08 03:55 UTC, sed-i commented on 0.110.0/rockcraft.yaml
> +    source-tag: v0.110.0
@lucabello, I forget what were your findings re [`craftctl set version`](https://snapcraft.io/docs/using-craftctl) for rocks.
Iirc we were discussing in the past if we could avoid specifying the version twice.

2025-01-08 03:55 UTC, sed-i commented on 0.110.0/rockcraft.yaml
> +      - ca-certificates
So turns out we do need certs to build? Should we add a comment why it's needed?

2025-01-08 03:55 UTC, sed-i commented on goss.yaml
> +    - _daemon_
This seems brittle.
It would make sense to keep this assertion if the _daemon_ user is some user facing functional promise, but iiuc the name and uid don't matter outside the container..?

I would however add an assertion for a port being bound.

2025-01-08 03:55 UTC, sed-i commented on goss.yaml
> +    group: root
This combo seems odd:
- owner is root but 0644 implies `o+r`; and
- the service is run as non-root, so able to read thanks to the `o+r`.

Not sure what the best practice is. Upstream has this:

![image](https://github.com/user-attachments/assets/80588cc1-0d61-4ec7-a001-1c52dc3dd4b1)

2025-01-08 09:19 UTC, lucabello commented on 0.110.0/rockcraft.yaml
> +    source-tag: v0.110.0
I don't think we explored that for rocks, only for charms :)

2025-01-08 09:20 UTC, lucabello commented on goss.yaml
> +user:
I would personally only have the check on the process running + probing any http endpoint, also to be aligned with our other rocks

2025-01-08 09:22 UTC, lucabello commented on README.md
> +* releasing to GHCR at [ghcr.io/canonical/otelcol:dev](https://ghcr.io/canonical/otelcol:dev), when merging to main, for development purposes.
We should publish to `ghcr.io/canonical/opentelemetry-collector:dev`; we usually keep the same name as OCI Factory for GHCR as well

2025-01-08 09:27 UTC, lucabello commented on justfile
> +  echo "Packing otelcol: $version"
very minor nitpick:

```suggestion
  echo "Packing opentelemetry-collector: $version"
```

2025-01-08 09:27 UTC, lucabello commented on justfile
> +  echo "Cleaning otelcol: $version"
very minor nitpick:

```suggestion
  echo "Cleaning opentelemetry-collector: $version"
```

2025-01-08 09:31 UTC, lucabello commented
Note that currently the container is stuck in `Pending`; make sure to execute `just test 0.110.0` manually and that it works as expected :)

2025-01-08 12:18 UTC, Abuelodelanada commented on README.md
> +* releasing to GHCR at [ghcr.io/canonical/otelcol:dev](https://ghcr.io/canonical/otelcol:dev), when merging to main, for development purposes.
Yes, we should use `opentelemetry-collector`.... `otelcol` is the name of the binary.

2025-01-08 13:34 UTC, Abuelodelanada commented on 0.110.0/rockcraft.yaml
> +      - ca-certificates
No, this is a leftover. Removed.

2025-01-08 14:29 UTC, Abuelodelanada commented on goss.yaml
> +    group: root
upstream has: `-rw-r--r--` and we have the same:


```shell
_daemon_@0997a5f7f341:/$ ls -lh /etc/otelcol/config.yaml
-rw-r--r-- 1 root root 1.5K Jan  8 13:40 /etc/otelcol/config.yaml
```

About the owner and group, do you think it should be other than `root`?

2025-01-08 19:59 UTC, Abuelodelanada commented on 0.110.0/rockcraft.yaml
> +  amd64:
See https://github.com/canonical/opentelemetry-collector-rock/issues/2

2025-01-08 22:07 UTC, Abuelodelanada commented on 0.110.0/rockcraft.yaml
> +    source-tag: v0.110.0
I think it is not possible.
This modification end up in a `rockcraft pack` error:

```diff
@@ -4,7 +4,7 @@ summary: Crucial component in the OpenTelemetry ecosystem.
 description: |
   Designed to collect, process, and export telemetry data such as metrics, logs,
   and traces from various sources to multiple destinations.
-version: "0.110.0"
+#version: "0.110.0"
 base: ubuntu@24.04
 license: Apache-2.0
 platforms:
@@ -22,12 +22,15 @@ parts:
     plugin: nil
     source: https://github.com/open-telemetry/opentelemetry-collector-releases
     source-type: git
-    source-tag: v0.110.0
+    #source-tag: v0.110.0
     build-snaps:
       - go/1.23/stable
     build-environment:
       - CGO_ENABLED: 0
       - GOOS: linux
+    override-pull: |
+      craftctl default
+      craftctl set version=v0.110.0
```

2025-01-10 15:52 UTC, sed-i commented on 0.110.0/rockcraft.yaml
> +        mode: "644"
Should this be 600?

2025-01-10 15:52 UTC, sed-i commented on goss.yaml
> +    skip: false
- Should we add a comment here or elsewhere about the purpose of each port?
- Should we have [tcp, tcp6 or both](https://goss.readthedocs.io/en/stable/gossfile/?h=tcp6#port)?

2025-01-10 15:52 UTC, sed-i commented on goss.yaml
>      group: root
Should these be updated according to:
```yaml
        owner: 584792
        group: 584792
```
?

And if the test passed with these assertions in place then maybe we have a problem with our `organize`?

2025-01-10 22:54 UTC, Abuelodelanada commented on goss.yaml
> +    skip: false
I need to better understand how otelcol works... so far I've discovered that all the open ports are tcp6.

For now I'll test these:

```yaml
port:
  # otlp receiver grpc
  tcp6:4317:
    listening: true
    port: 'tcp6:4317'
    skip: false

  # otlp receiver http
  tcp6:4318:
    listening: true
    port: 'tcp6:4318'
    skip: false

  # prometheus receiver http
  tcp6:8888:
    listening: true
    port: 'tcp6:8888'
    skip: false
```

2025-01-10 22:56 UTC, Abuelodelanada commented
Test output:

```shell
$ just test 0.110.0
Pushing opentelemetry-collector 0.110.0 to local registry
Getting image source signatures
Copying blob de44b265507a done   | 
Copying blob 85ea6ed8fcb3 done   | 
Copying blob 901b64f9bf49 done   | 
Copying blob e4329a4fa04b done   | 
Copying blob e15aea7a56ec done   | 
Copying config 57813cff4e done   | 
Writing manifest to image destination
INFO: Starting docker container
INFO: Container ID: ccc2f0ee
INFO: Sleeping for 0.2
INFO: Container health
INFO: Running Tests
............

Total Duration: 0.008s
Count: 12, Failed: 0, Skipped: 0
INFO: Deleting container
```

2025-01-13 16:10 UTC, Abuelodelanada commented
Hi @deusebio

Please, may we have you review here?
Is it enough if we build the image using bare [`otelcol` distribution](https://github.com/canonical/opentelemetry-collector-rock/blob/739f5a1c21b615f076669fc6bce240c80ac07f9c/0.110.0/rockcraft.yaml#L32)?

2025-01-14 06:04 UTC, sed-i approved these changes

2025-01-14 06:04 UTC, sed-i commented on 0.110.0/rockcraft.yaml
> +    source-tag: v0.110.0
The missing section in your diff is:
```yaml
adopt-info: otelcol
```
but this is not a priority. I imagine it would also involve update CI, which is out of scope for this issue.

2025-01-14 16:24 UTC, orfeas-k requested changes
Left a first comment but I need to go through the rockcraft in more detail as I didn't have the time today, will do tomorrow morning.

2025-01-14 20:44 UTC, Abuelodelanada commented on 0.110.0/rockcraft.yaml
> +    command: "/usr/bin/otelcol --config /etc/otelcol/config.yaml"
Good catch @orfeas-k !

Keep in mind that in order to use custom config file(s) you need to mount them in the container with the `-v` argument, like this:

```shell
docker run --rm -v "$(pwd)":/tmp/local --name otel localhost:32000/opentelemetry-collector:0.110.0 --config /tmp/local/config-local.yaml --config /tmp/local/config-local2.yaml
2025-01-14T20:39:01.763Z [pebble] Started daemon.
2025-01-14T20:39:01.777Z [pebble] POST /v1/services 7.011011ms 202
2025-01-14T20:39:01.784Z [pebble] Service "otelcol" starting: /usr/bin/otelcol [ --config /tmp/local/config-local.yaml --config /tmp/local/config-local2.yaml ]
2025-01-14T20:39:02.798Z [pebble] GET /v1/changes/1/wait 1.02072893s 200
2025-01-14T20:39:02.799Z [pebble] Started default services with change 1.
```

Now in the container you will see `otelcol` using more than one config file:

```shell
_daemon_@1f8b47229afa:/$ ps ax
    PID TTY      STAT   TIME COMMAND
      1 ?        Ssl    0:00 /usr/bin/pebble enter --args otelcol --config /tmp/local/config-local.yaml --config /tmp/local/con
     15 ?        Sl     0:00 /usr/bin/otelcol --config /tmp/local/config-local.yaml --config /tmp/local/config-local2.yaml
     28 pts/0    Ss     0:00 bash
     34 pts/0    R+     0:00 ps ax
```


But if you run the image without custom config files, the image uses the default one:

```shell
docker run --rm --name otel localhost:32000/opentelemetry-collector:0.110.0 
2025-01-14T20:43:04.727Z [pebble] Started daemon.
2025-01-14T20:43:04.745Z [pebble] POST /v1/services 7.09481ms 202
2025-01-14T20:43:04.751Z [pebble] Service "otelcol" starting: /usr/bin/otelcol [ --config /etc/otelcol/config.yaml ]
2025-01-14T20:43:05.766Z [pebble] GET /v1/changes/1/wait 1.020257149s 200
2025-01-14T20:43:05.766Z [pebble] Started default services with change 1.
```

and in the container:

```shell
_daemon_@d1178ec9189f:/$ ps axf
    PID TTY      STAT   TIME COMMAND
     28 pts/0    Ss     0:00 bash
     35 pts/0    R+     0:00  \_ ps axf
      1 ?        Ssl    0:00 /usr/bin/pebble enter --args otelcol --config /etc/otelcol/config.yaml
     15 ?        Sl     0:00 /usr/bin/otelcol --config /etc/otelcol/config.yaml
```

2025-01-15 09:03 UTC, orfeas-k approved these changes
Left a small suggestion but LGTM already

2025-01-15 09:03 UTC, orfeas-k commented on 0.110.0/rockcraft.yaml
> +    command: "/usr/bin/otelcol --config /etc/otelcol/config.yaml"
ACK, thank @Abuelodelanada for the walkthourgh:) 

Tested in the deployment of our charm and it's working!

```
$ kf exec otel-collector-5f4469dd68-xvg44 -- pebble logs -n=all
2025-01-15T08:56:09.110Z [otelcol] 2025-01-15T08:56:09.110Z	info	service@v0.110.0/service.go:137	Setting up own telemetry...
2025-01-15T08:56:09.110Z [otelcol] 2025-01-15T08:56:09.110Z	info	service@v0.110.0/service.go:186	Skipped telemetry setup.
2025-01-15T08:56:09.112Z [otelcol] 2025-01-15T08:56:09.112Z	info	service@v0.110.0/service.go:208	Starting otelcol...	{"Version": "0.110.0", "NumCPU": 8}
2025-01-15T08:56:09.112Z [otelcol] 2025-01-15T08:56:09.112Z	info	extensions/extensions.go:39	Starting extensions...
2025-01-15T08:56:09.112Z [otelcol] 2025-01-15T08:56:09.112Z	info	extensions/extensions.go:42	Extension is starting...	{"kind": "extension", "name": "zpages"}
2025-01-15T08:56:09.112Z [otelcol] 2025-01-15T08:56:09.112Z	info	zpagesextension@v0.110.0/zpagesextension.go:55	Registered zPages span processor on tracer provider	{"kind": "extension", "name": "zpages"}
2025-01-15T08:56:09.112Z [otelcol] 2025-01-15T08:56:09.112Z	info	zpagesextension@v0.110.0/zpagesextension.go:65	Registered Host's zPages	{"kind": "extension", "name": "zpages"}
2025-01-15T08:56:09.113Z [otelcol] 2025-01-15T08:56:09.112Z	info	zpagesextension@v0.110.0/zpagesextension.go:77	Starting zPages extension	{"kind": "extension", "name": "zpages", "config": {"Endpoint":"localhost:55679","TLSSetting":null,"CORS":null,"Auth":null,"MaxRequestBodySize":0,"IncludeMetadata":false,"ResponseHeaders":null,"CompressionAlgorithms":null,"ReadTimeout":0,"ReadHeaderTimeout":0,"WriteTimeout":0,"IdleTimeout":0}}
2025-01-15T08:56:09.113Z [otelcol] 2025-01-15T08:56:09.113Z	info	extensions/extensions.go:59	Extension started.	{"kind": "extension", "name": "zpages"}
2025-01-15T08:56:09.113Z [otelcol] 2025-01-15T08:56:09.113Z	info	extensions/extensions.go:42	Extension is starting...	{"kind": "extension", "name": "pprof"}
2025-01-15T08:56:09.113Z [otelcol] 2025-01-15T08:56:09.113Z	info	pprofextension@v0.110.0/pprofextension.go:61	Starting net/http/pprof server	{"kind": "extension", "name": "pprof", "config": {"TCPAddr":{"Endpoint":"localhost:1777","DialerConfig":{"Timeout":0}},"BlockProfileFraction":0,"MutexProfileFraction":0,"SaveToFile":""}}
2025-01-15T08:56:09.113Z [otelcol] 2025-01-15T08:56:09.113Z	info	extensions/extensions.go:59	Extension started.	{"kind": "extension", "name": "pprof"}
2025-01-15T08:56:09.113Z [otelcol] 2025-01-15T08:56:09.113Z	info	extensions/extensions.go:42	Extension is starting...	{"kind": "extension", "name": "health_check"}
2025-01-15T08:56:09.113Z [otelcol] 2025-01-15T08:56:09.113Z	info	healthcheckextension@v0.110.0/healthcheckextension.go:33	Starting health_check extension	{"kind": "extension", "name": "health_check", "config": {"Endpoint":"localhost:13133","TLSSetting":null,"CORS":null,"Auth":null,"MaxRequestBodySize":0,"IncludeMetadata":false,"ResponseHeaders":null,"CompressionAlgorithms":null,"ReadTimeout":0,"ReadHeaderTimeout":0,"WriteTimeout":0,"IdleTimeout":0,"Path":"/","ResponseBody":null,"CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2025-01-15T08:56:09.113Z [otelcol] 2025-01-15T08:56:09.113Z	info	extensions/extensions.go:59	Extension started.	{"kind": "extension", "name": "health_check"}
2025-01-15T08:56:09.113Z [otelcol] 2025-01-15T08:56:09.113Z	warn	internal@v0.110.0/warning.go:40	Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks.	{"kind": "exporter", "data_type": "metrics", "name": "prometheus", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks"}
2025-01-15T08:56:09.113Z [otelcol] 2025-01-15T08:56:09.113Z	warn	internal@v0.110.0/warning.go:40	Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks.	{"kind": "receiver", "name": "opencensus", "data_type": "metrics", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks"}
2025-01-15T08:56:09.115Z [otelcol] 2025-01-15T08:56:09.115Z	info	healthcheck/handler.go:132	Health Check state change	{"kind": "extension", "name": "health_check", "status": "ready"}
2025-01-15T08:56:09.115Z [otelcol] 2025-01-15T08:56:09.115Z	info	service@v0.110.0/service.go:234	Everything is ready. Begin running and processing data.
```

2025-01-15 09:03 UTC, orfeas-k commented on 0.110.0/rockcraft.yaml
> +      opt/otelcol/config.yaml: etc/otelcol/config.yaml
well just noticed https://github.com/canonical/opentelemetry-collector-rock/pull/1#discussion_r1904515809 :smile:

2025-01-15 14:50 UTC, merged